version: '2.1'

services:

  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        - YII_ENV=${YII_ENV}
        - ENV=dev
    image: 'pricing:app'
    env_file:
      - .env
      - .env.local
    ports:
      - 9000
      - ${APP_WS:-8891}:8891
      - ${APP_WSS:-8892}:8892
      - ${APP_PORT:-80}:80
      - ${APP_PORT_SSL:-443}:443
    volumes:
      - .:/app:delegated
      - ./docker/hosts/test:/hosts:delegated
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    container_name: 'postgres'
    restart: always
    build:
      context: docker/postgres
    image: 'pricing:postgres'
    env_file:
      - .env
      - .env.local
    ports: ['${MASTER_EXTERNAL_PORT:-5432}:5432']
    volumes:
      - './pg_data/:${PGDATA:-/var/lib/postgresql/data}'

  rabbitmq:
    image: 'rabbitmq:3-management'
    restart: 'on-failure'
    env_file:
      - .env
      - .env.local
    ports:
      - ${RABBIT_PORT:-5672}:5672
      - 15672:15672
